import type {
  StrategyGoal,
  CandidateWorkflow,
  WorkflowSpec,
  WorkflowNode,
  WorkflowEdge,
  Result,
} from '@strategyforge/core';
import { ok, err } from '@strategyforge/core';
import { supplyActionFor, withdrawActionFor } from './protocol-registry.js';

// ─── Types ───────────────────────────────────────────────────────

export interface CompilerOutput {
  workflowSpec: WorkflowSpec;
  gasEstimate: number; // estimated monthly USD cost
}

// KeeperHub action type interface (subset we need from the keeperhub package)
interface ActionSchema {
  type: string;
  category?: string;
}

interface ActionSchemaSource {
  listActionSchemas(): Promise<Result<ActionSchema[]>>;
}

// ─── Gas estimation constants ─────────────────────────────────────
const GAS_PER_ACTION = 150_000;     // estimated gas units per supply/withdraw
const GAS_PRICE_GWEI = 20;          // 20 gwei (conservative estimate)
const ETH_PRICE_USD = 3_000;        // rough estimate for gas cost calculation
const RUNS_PER_MONTH = 120;         // 4 runs/day × 30 days (6h cron)

// ─── Compiler ────────────────────────────────────────────────────

export class Compiler {
  private knownTypes = new Set<string>();
  private initialized = false;

  constructor(private readonly keeperhub: ActionSchemaSource) { }

  async init(): Promise<Result<void>> {
    const result = await this.keeperhub.listActionSchemas();
    if (!result.ok) {
      // Non-fatal: fall back to registry-based mapping + code/run-code fallback
      console.warn('[Compiler] list_action_schemas failed — using registry fallback:', result.error.message);
      this.initialized = true;
      return ok(undefined);
    }
    for (const schema of result.value) {
      this.knownTypes.add(schema.type);
    }
    this.initialized = true;
    return ok(undefined);
  }

  compile(params: {
    selectedCandidate: CandidateWorkflow;
    constraints: string[];
    goal: StrategyGoal;
  }): CompilerOutput {
    if (!this.initialized) {
      throw new Error('Compiler.init() must be called before compile()');
    }
    const { selectedCandidate, goal } = params;

    const workflowSpec: WorkflowSpec = {
      name: `StrategyForge — ${goal.asset} ${goal.riskLevel} strategy`,
      description: `Automated workflow node topology. Generated by StrategyForge pipeline.`,
      trigger: selectedCandidate.trigger ?? {
        type: 'schedule',
        config: { cron: '0 */6 * * *' }, // every 6 hours
      },
      nodes: selectedCandidate.nodes,
      edges: selectedCandidate.edges,
    };

    const gasEstimate = computeGasEstimate(selectedCandidate.nodes.length);

    return { workflowSpec, gasEstimate };
  }

  private resolveActionType(protocol: string): string {
    // 1. Check registry for known native action type
    const registryType = supplyActionFor(protocol);
    if (registryType && (this.knownTypes.size === 0 || this.knownTypes.has(registryType))) {
      return registryType;
    }

    // 2. Try common naming patterns for protocols not in registry
    const candidates = [
      `${protocol}/supply`,
      `${protocol}/vault-deposit`,
      `${protocol}/deposit`,
    ];
    for (const candidate of candidates) {
      if (this.knownTypes.has(candidate)) return candidate;
    }

    // 3. Fall back to code/run-code — a KeeperHub universal action
    return 'code/run-code';
  }

  private buildSupplyNode(
    nodeId: string,
    actionType: string,
    protocol: string,
    chain: string,
    asset: string,
    amountUSD: number,
  ): WorkflowNode {
    if (actionType === 'code/run-code') {
      // Generic fallback: JavaScript that calls the protocol's supply function
      return {
        id: nodeId,
        type: 'code/run-code',
        config: {
          code: buildFallbackCode(protocol, chain, asset, amountUSD),
        },
      };
    }

    // Native protocol action — config shape follows KeeperHub schema
    const config: Record<string, unknown> = {
      asset,
      amount: amountUSD.toFixed(2),
      onBehalfOf: '{{wallet.address}}',
    };

    // Vault-style protocols use 'assets' not 'amount'
    if (actionType.includes('vault-deposit')) {
      config.assets = amountUSD.toFixed(2);
      delete config.amount;
      delete config.onBehalfOf;
    }

    // Network/chain field
    config.network = chainToNetworkId(chain);

    return { id: nodeId, type: actionType, config };
  }
}

// ─── Helpers ─────────────────────────────────────────────────────

function computeGasEstimate(nodeCount: number): number {
  const gasUnits = nodeCount * GAS_PER_ACTION * RUNS_PER_MONTH;
  const ethCost = (gasUnits * GAS_PRICE_GWEI * 1e-9);
  return Math.round(ethCost * ETH_PRICE_USD * 100) / 100;
}

function chainToNetworkId(chain: string): string {
  const map: Record<string, string> = {
    ethereum: '1',
    base: '8453',
    arbitrum: '42161',
    optimism: '10',
    polygon: '137',
    avalanche: '43114',
  };
  return map[chain.toLowerCase()] ?? chain;
}

function buildFallbackCode(protocol: string, chain: string, asset: string, amountUSD: number): string {
  return `// Fallback: ${protocol} supply on ${chain}
// StrategyForge could not find a native KeeperHub action for "${protocol}"
// This code must be reviewed and updated with the correct contract address + ABI

const amount = "${amountUSD.toFixed(2)}"; // USD amount
const asset = "${asset}";
const chain = "${chain}";

// TODO: Replace with actual protocol contract call
return { protocol: "${protocol}", asset, amount, chain, status: "pending_manual_config" };`;
}
